services:
  backend:
    build:
      context: .
      dockerfile: scraper-backend/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - scraper-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: scraper-frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - scraper-network
    restart: unless-stopped

networks:
  scraper-network:
    driver: bridge
