services:
  backend:
    build:
      context: .
      dockerfile: scrapper-backend/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - scrapper-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: scrapper-frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - scrapper-network
    restart: unless-stopped

networks:
  scrapper-network:
    driver: bridge
